name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Sync Learning Timeline to Azure
        if: contains(github.event.head_commit.message, 'learning') || contains(github.event.head_commit.modified, 'site/data/learning-timeline.json')
        shell: pwsh
        run: |
          # Install Az.Storage module
          Install-Module -Name Az.Storage -Force -Scope CurrentUser
          
          # Authenticate with Azure using service principal
          $securePassword = ConvertTo-SecureString -String "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $securePassword)
          Connect-AzAccount -ServicePrincipal -Credential $credential -TenantId "${{ secrets.AZURE_TENANT_ID }}"
          
          # Run the sync script
          ./scripts/Update-CloudResumeLearning.ps1 -UpdateMainIndex

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/site"
          api_location: "/api"
          output_location: ""
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        run: echo "Skipping deploy for closed pull request."
