name: Sync Learning Timeline to Azure Blob

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'site/index.html'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-learning:
    runs-on: ubuntu-latest
    
    # Only run if index.html changes include learning section updates
    if: contains(github.event.head_commit.message, 'learning') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout cloud-resume
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: cloud-resume

    - name: Checkout pwsh_honeypot for sync script
      uses: actions/checkout@v4
      with:
        repository: sockpuppetrebel/pwsh_honeypot
        path: pwsh_honeypot
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup PowerShell
      shell: bash
      run: |
        # PowerShell is pre-installed on GitHub runners
        pwsh --version

    - name: Install Azure PowerShell Module
      shell: pwsh
      run: |
        Install-Module -Name Az.Storage -Force -AllowClobber -Scope CurrentUser
        Import-Module Az.Storage

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Learning Timeline Sync
      shell: pwsh
      env:
        AZURE_STORAGE_ACCOUNT: jslaterdevjournal
        AZURE_CONTAINER: claude-development-journal
      run: |
        Write-Host "Starting learning timeline sync..." -ForegroundColor Cyan
        
        # Run the sync script
        $syncScript = "./pwsh_honeypot/scripts/azure/Sync-LearningTimeline-ToBlob.ps1"
        $htmlPath = "./cloud-resume/site/index.html"
        
        # Execute sync
        & $syncScript -HtmlPath $htmlPath -UpdateIndex -Verbose
        
        Write-Host "Sync completed successfully!" -ForegroundColor Green

    - name: Upload Sync Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-log
        path: cloud-resume/site/learning-timeline-backup.json
        retention-days: 30